services:
  arc-fusion-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=dev
    env_file:
      - .env.dev
    networks:
      - arc-fusion-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - arc-fusion-network

volumes:
  redis-volume:
    driver: local
networks:
  arc-fusion-network:
    driver: bridge