name: arcfusion-asm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23
  - openjdk=17
  - fastapi>=0.111
  - uvicorn
  - pydantic>=2.7,<3
  - gunicorn
  - poppler
  - pip:
      - openai
      - python-dotenv
      - pyyaml
      - langchain>=0.2.2
      - langchain-community
      - langchain-anthropic
      - langgraph>=0.2
      - langsmith
      - requests
      - coloredlogs
      - python-json-logger
      - langchain-openai>=0.2.0
      - langchain-deepseek
      - numpy
      - chromadb
      - psycopg2-binary
      - asyncpg
      - sqlalchemy[asyncio]>=2.0
      - llama-index
      - llama-index-vector-stores-chroma
      - "unstructured[pdf]"
